INSERT INTO pages VALUES("1","index","Главная","10","0","1","","1","<p>\r\n	Текст первой страницы.</p>\r\n","1","1","0","empty","0","","","");
INSERT INTO pages VALUES("2","e404","404","1600","0","1","","1","<p>\r\n	Ошибка 404. Блин.&nbsp;</p>\r\n","0","0","0","empty","1","","","");INSERT INTO options VALUES("1","site_title","Название сайта","100","14","0","Название сайта","1");
INSERT INTO options VALUES("2","keywords","Ключевые слова","200","14","0","","2");
INSERT INTO options VALUES("14","seo","SEO","50","0","1","","");
INSERT INTO options VALUES("6","description","description","300","14","0","","2");
INSERT INTO options VALUES("7","f_bread","Самая первая хлебная крошка","20","0","0","Главная","1");
INSERT INTO options VALUES("11","counters","Счетчики","10","0","0","","2");
INSERT INTO options VALUES("19","mail","Адрес электронной почты","30","0","0","demo@mail.ru","1");
INSERT INTO options VALUES("20","header_code","Текст в конце header","1400","14","0","","2");
INSERT INTO options VALUES("21","footer_code","Текст в конце footer","1500","14","0","","2");INSERT INTO users VALUES("1","administrator_sayta","Администратор сайта","200","0","0","admin","dima.am@mail.ru","1","21232f297a57a5a743894a0e4a801fc3","f09409e7d9e6c1f7804fe3ed3e410493;08094aca49415d6835d3367e2897563f","");
INSERT INTO users VALUES("3","editor","editor","400","0","0","editor","dima.am@mail.ru","0","5aee9dbd2a188839105073571bee1b1f","","");INSERT INTO templates VALUES("1","main","Основной шаблон","20","0","0");
INSERT INTO templates VALUES("2","empty","Пустой","30","0","0");
INSERT INTO templates VALUES("5","_","[наследуемый]","10","0","0");INSERT INTO modules VALUES("1","empty","Текстовая страница","100","0","0");INSERT INTO options_class VALUES("1","text","Текстовая строка","100","0","0");
INSERT INTO options_class VALUES("2","text2","Текстовой редактор","200","0","0");
INSERT INTO options_class VALUES("3","wis","Визуальный редактор","300","0","0");
INSERT INTO options_class VALUES("4","check","Чекбокс","400","0","0");
INSERT INTO options_class VALUES("5","pic","Картинка","500","0","0");
INSERT INTO options_class VALUES("6","file","Файл","600","0","0");INSERT INTO system_user_groups VALUES("1","admin","Админы","100","0","0","pages;system_user_groups;options;users;templates;modules;cms_options;options_class;journal","pages;system_user_groups;options;users;templates;modules;cms_options;options_class;journal","pages;system_user_groups;options;users;templates;modules;cms_options;options_class;journal","pages;system_user_groups;options;users;templates;modules;cms_options;options_class;journal");
INSERT INTO system_user_groups VALUES("2","redaktor","Редактор","200","0","0","pages;system_user_groups;options;users;templates;modules;cms_options;options_class;journal","pages;system_user_groups;options;users;templates;modules;cms_options;options_class;journal","pages;system_user_groups;options;users;templates;modules;cms_options;options_class;journal","pages;system_user_groups;options;users;templates;modules;cms_options;options_class;journal");