DROP TABLE IF EXISTS cms_options;
CREATE TABLE `cms_options` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` text CHARACTER SET cp1251 NOT NULL,  `caption` text CHARACTER SET cp1251 NOT NULL,  `sort` int(11) NOT NULL,  `parent` int(11) NOT NULL,  `folder` int(11) NOT NULL,  `opt_block` text NOT NULL,  `opt_sort` text NOT NULL,  `opt_by` text NOT NULL,  `opt_count` int(11) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS journal;
CREATE TABLE `journal` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` text NOT NULL,  `caption` text NOT NULL,  `sort` int(11) NOT NULL,  `parent` int(11) NOT NULL,  `folder` int(11) NOT NULL,  `user_id` text NOT NULL,  `block_name` text NOT NULL,  `item_id` int(11) NOT NULL,  `action` text NOT NULL,  `data_after` longtext NOT NULL,  `data_before` longtext NOT NULL,  `date_time` datetime NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=cp1251;
DROP TABLE IF EXISTS modules;
CREATE TABLE `modules` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` text NOT NULL,  `caption` text NOT NULL,  `sort` int(11) NOT NULL,  `parent` int(11) NOT NULL,  `folder` int(11) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=cp1251;
INSERT INTO modules VALUES("1","empty","Текстовая страница","100","0","0");
DROP TABLE IF EXISTS options;
CREATE TABLE `options` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` text NOT NULL,  `caption` text NOT NULL,  `sort` int(11) NOT NULL,  `parent` int(11) NOT NULL,  `folder` int(11) NOT NULL,  `hvalue` text NOT NULL,  `options_class` text NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=23 DEFAULT CHARSET=cp1251;
INSERT INTO options VALUES("1","site_title","Название сайта","100","14","0","Название сайта","1");
INSERT INTO options VALUES("2","keywords","Ключевые слова","200","14","0","","2");
INSERT INTO options VALUES("14","seo","SEO","50","0","1","","");
INSERT INTO options VALUES("6","description","description","300","14","0","","2");
INSERT INTO options VALUES("7","f_bread","Самая первая хлебная крошка","20","0","0","Главная","1");
INSERT INTO options VALUES("11","counters","Счетчики","10","0","0","","2");
INSERT INTO options VALUES("19","mail","Адрес электронной почты","30","0","0","demo@mail.ru","1");
INSERT INTO options VALUES("20","header_code","Текст в конце header","1400","14","0","","2");
INSERT INTO options VALUES("21","footer_code","Текст в конце footer","1500","14","0","","2");
DROP TABLE IF EXISTS options_class;
CREATE TABLE `options_class` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` text NOT NULL,  `caption` text NOT NULL,  `sort` int(11) NOT NULL,  `parent` int(11) NOT NULL,  `folder` int(11) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=cp1251;
INSERT INTO options_class VALUES("1","text","Текстовая строка","100","0","0");
INSERT INTO options_class VALUES("2","text2","Текстовой редактор","200","0","0");
INSERT INTO options_class VALUES("3","wis","Визуальный редактор","300","0","0");
INSERT INTO options_class VALUES("4","check","Чекбокс","400","0","0");
INSERT INTO options_class VALUES("5","pic","Картинка","500","0","0");
INSERT INTO options_class VALUES("6","file","Файл","600","0","0");
DROP TABLE IF EXISTS pages;
CREATE TABLE `pages` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` text NOT NULL,  `caption` text NOT NULL,  `sort` int(11) NOT NULL,  `parent` int(11) NOT NULL,  `folder` int(11) NOT NULL,  `keywords` text NOT NULL,  `template` int(11) NOT NULL,  `detail_text` text NOT NULL,  `in_menu` smallint(6) NOT NULL,  `human_url` smallint(6) NOT NULL,  `not_visible` smallint(6) NOT NULL,  `modules` text NOT NULL,  `not_in_bread` smallint(6) NOT NULL,  `caption2` text NOT NULL,  `description` text NOT NULL,  `redirect` text NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=36 DEFAULT CHARSET=cp1251;
INSERT INTO pages VALUES("1","index","Главная","10","0","1","","1","<p>\r\n	Текст первой страницы.</p>\r\n","1","1","0","empty","0","","","");
INSERT INTO pages VALUES("2","e404","404","1600","0","1","","1","<p>\r\n	Ошибка 404. Блин.&nbsp;</p>\r\n","0","0","0","empty","1","","","");
DROP TABLE IF EXISTS system_cache;
CREATE TABLE `system_cache` (  `id` varchar(255) NOT NULL,  `value` text NOT NULL,  `time` int(11) NOT NULL,  `module` text NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=cp1251;
DROP TABLE IF EXISTS system_data_block;
CREATE TABLE `system_data_block` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` tinytext CHARACTER SET cp1251 NOT NULL,  `bgroup` int(11) NOT NULL,  `caption` text CHARACTER SET cp1251 NOT NULL,  `sort` int(11) NOT NULL,  `fav` tinyint(1) NOT NULL,  `hide_folders` tinyint(1) NOT NULL,  `hide_folders2` tinyint(1) NOT NULL,  `hide_code` tinyint(1) NOT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `name` (`name`(255))) ENGINE=MyISAM AUTO_INCREMENT=42 DEFAULT CHARSET=latin1;
INSERT INTO system_data_block VALUES("12","templates","1","Шаблоны","600","0","1","0","0");
INSERT INTO system_data_block VALUES("11","pages","15","Страницы","300","1","0","0","0");
INSERT INTO system_data_block VALUES("8","users","1","Пользователи","200","0","1","0","1");
INSERT INTO system_data_block VALUES("7","options","1","Настройки","100","0","0","1","0");
INSERT INTO system_data_block VALUES("17","modules","1","Модули сайта","800","0","1","0","0");
INSERT INTO system_data_block VALUES("24","cms_options","1","Настройки админки","1200","0","1","0","0");
INSERT INTO system_data_block VALUES("27","options_class","1","Типы полей настроек сайта","1500","0","1","0","0");
INSERT INTO system_data_block VALUES("40","journal","1","Журнал","2100","0","1","1","1");
DROP TABLE IF EXISTS system_data_block_fields;
CREATE TABLE `system_data_block_fields` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `data_block` int(11) NOT NULL,  `name` tinytext CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,  `caption` tinytext NOT NULL,  `type` int(11) NOT NULL,  `sort` int(11) NOT NULL,  `required` tinyint(4) NOT NULL,  `multiple` tinyint(4) NOT NULL,  `dgroup` int(11) NOT NULL,  `owner_type` tinyint(4) NOT NULL,  `add_values` text NOT NULL,  `not_list` tinyint(4) NOT NULL,  `admin_only` tinyint(4) NOT NULL,  `meta` tinyint(4) NOT NULL,  `not_element` tinyint(1) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=157 DEFAULT CHARSET=cp1251;
INSERT INTO system_data_block_fields VALUES("24","8","email","E-mail","1","900","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("55","8","block_control","Имеет доступ к настройкам блоков","7","2600","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("54","11","modules","Модуль сайта","15","1410","0","0","0","1","modules;name;caption","0","1","0","0");
INSERT INTO system_data_block_fields VALUES("78","8","pass","Пароль","13","120","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("18","8","login","Логин","1","100","1","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("51","11","human_url","ЧПУ","7","1900","0","0","0","1","","1","1","0","0");
INSERT INTO system_data_block_fields VALUES("52","11","not_visible","Невидимость","7","1420","0","0","0","1","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("30","7","hvalue","Значение","5","200","0","0","0","0","","1","0","0","0");
INSERT INTO system_data_block_fields VALUES("46","11","keywords","Ключевые слова","1","1400","0","0","0","1","","1","0","1","0");
INSERT INTO system_data_block_fields VALUES("47","11","template","Шаблон","15","1400","0","0","0","1","templates;id;caption","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("49","11","detail_text","Текст страницы","5","2500","0","0","0","1","","1","0","0","0");
INSERT INTO system_data_block_fields VALUES("50","11","in_menu","Попадает в меню","7","1800","0","0","0","1","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("72","11","not_in_bread","НЕ попадает в навигационную строку","7","1850","0","0","0","1","","1","0","0","0");
INSERT INTO system_data_block_fields VALUES("86","24","opt_block","Блок","1","4500","0","0","0","0","system_data_block;id;caption","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("87","24","opt_sort","Сортировка","1","4600","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("88","24","opt_by","Направление сортировки","1","4700","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("89","24","opt_count","Число элементов","1","4800","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("91","11","caption2","title","1","10","0","0","0","1","","1","0","1","0");
INSERT INTO system_data_block_fields VALUES("92","11","description","description","4","20","0","0","0","1","","1","0","1","0");
INSERT INTO system_data_block_fields VALUES("99","11","redirect","Переход вместо страницы","1","2450","0","0","0","1","","1","0","0","0");
INSERT INTO system_data_block_fields VALUES("104","7","options_class","options_class","15","5600","0","0","0","0","options_class;id;caption","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("117","28","caption2","Заголовок","1","6500","0","0","0","1","","1","0","1","0");
INSERT INTO system_data_block_fields VALUES("116","28","detail_text","Детальный текст","5","6400","0","0","0","0","","1","0","0","0");
INSERT INTO system_data_block_fields VALUES("109","35","pic2","pic2","6","6100","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("139","37","other","Подобные товары","8","8700","0","1","0","0","catalog;id;caption","1","0","0","0");
INSERT INTO system_data_block_fields VALUES("115","28","preview_text","Краткий текст","4","6300","0","0","0","0","","1","0","0","0");
INSERT INTO system_data_block_fields VALUES("140","28","sdate","Дата","11","10","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("118","28","description","Description","4","6600","0","0","0","1","","1","0","1","0");
INSERT INTO system_data_block_fields VALUES("119","28","keywords","Ключевые слова","4","6700","0","0","0","1","","1","0","1","0");
INSERT INTO system_data_block_fields VALUES("120","36","url","Ссылка","1","6800","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("121","36","foto","Картинка","6","6900","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("122","37","detail_text","Детальный текст","5","7000","0","0","0","0","","1","0","0","0");
INSERT INTO system_data_block_fields VALUES("123","37","cost","Цена","3","7100","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("124","37","foto","Фото","6","7200","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("125","37","foto_multi","Дополнительные фото","6","7300","0","1","0","0","","1","0","0","0");
INSERT INTO system_data_block_fields VALUES("126","37","spec1","Спец-предложение","7","7400","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("127","38","foto","Фото","6","7500","0","0","0","1","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("128","39","fio","ФИО","1","7600","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("155","39","uic_rec","uic_rec","1","10000","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("130","39","email","Электронная почта","1","7800","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("154","39","password","Пароль","13","9900","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("133","39","address","Адрес доставки","4","8100","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("135","39","uid","uid","1","8300","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("136","37","caption2","Заголовок","1","8400","0","0","0","1","","1","0","1","0");
INSERT INTO system_data_block_fields VALUES("137","37","description","Description","4","8500","0","0","0","1","","1","0","1","0");
INSERT INTO system_data_block_fields VALUES("138","37","keywords","Ключевые слова","4","8600","0","0","0","1","","1","0","1","0");
INSERT INTO system_data_block_fields VALUES("141","40","user_id","user_id","15","8800","0","0","0","0","users;id;login","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("142","40","block_name","block_name","1","8900","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("143","40","item_id","item_id","2","9000","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("144","40","action","action","1","9100","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("148","40","data_before","data_before","4","9300","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("147","40","data_after","data_after","4","9200","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("149","40","folder","folder","7","9400","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("150","40","date_time","date_time","12","9500","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("151","41","test0","test0","16","9600","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("153","28","foto","Фото","6","9800","0","0","0","0","","0","0","0","0");
INSERT INTO system_data_block_fields VALUES("156","37","tags","Тэги","14","10100","0","0","0","0","catalog;tags","1","0","0","0");
DROP TABLE IF EXISTS system_data_block_group;
CREATE TABLE `system_data_block_group` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `caption` tinytext NOT NULL,  `sort` int(11) NOT NULL,  `name` text NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=cp1251;
INSERT INTO system_data_block_group VALUES("1","Системные","300","system");
INSERT INTO system_data_block_group VALUES("15","Блоки сайта","50","main");
DROP TABLE IF EXISTS system_data_block_types;
CREATE TABLE `system_data_block_types` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` tinytext NOT NULL,  `caption` tinytext NOT NULL,  `basetype` tinytext NOT NULL,  `sort` int(11) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=cp1251;
INSERT INTO system_data_block_types VALUES("1","short_text","Текстовая строка","TEXT","100");
INSERT INTO system_data_block_types VALUES("2","integ","Целое число","INT","200");
INSERT INTO system_data_block_types VALUES("3","double_integ","Дробное число","DOUBLE","300");
INSERT INTO system_data_block_types VALUES("4","wysiwyg_text","Редактор текста","LONGTEXT","400");
INSERT INTO system_data_block_types VALUES("5","wysiwyg_html","Визуальный редактор текста","LONGTEXT","500");
INSERT INTO system_data_block_types VALUES("6","image","Картинка","TEXT","700");
INSERT INTO system_data_block_types VALUES("7","checkbox","Галочка","SMALLINT","800");
INSERT INTO system_data_block_types VALUES("8","list","Выпадающий список","TEXT","1000");
INSERT INTO system_data_block_types VALUES("9","element","Привязка к папке","INT","1100");
INSERT INTO system_data_block_types VALUES("10","folder","Привязка к элементу","INT","1200");
INSERT INTO system_data_block_types VALUES("11","ddate","Дата","DATE","1300");
INSERT INTO system_data_block_types VALUES("12","ddatetime","Дата и время","DATETIME","1400");
INSERT INTO system_data_block_types VALUES("13","pass","Пароль","TEXT","1500");
INSERT INTO system_data_block_types VALUES("14","tags","Тэги","TEXT","5000");
INSERT INTO system_data_block_types VALUES("15","list_need","Выпадающий список обяз.","TEXT","1005");
INSERT INTO system_data_block_types VALUES("16","file","Файл","TEXT","9000");
DROP TABLE IF EXISTS templates;
CREATE TABLE `templates` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` text NOT NULL,  `caption` text NOT NULL,  `sort` int(11) NOT NULL,  `parent` int(11) NOT NULL,  `folder` int(11) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=cp1251;
INSERT INTO templates VALUES("1","main","Основной шаблон","20","0","0");
INSERT INTO templates VALUES("2","empty","Пустой","30","0","0");
INSERT INTO templates VALUES("5","_","[наследуемый]","10","0","0");
DROP TABLE IF EXISTS users;
CREATE TABLE `users` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` text NOT NULL,  `caption` text NOT NULL,  `sort` int(11) NOT NULL,  `parent` int(11) NOT NULL,  `folder` int(11) NOT NULL,  `login` text NOT NULL,  `email` text NOT NULL,  `block_control` smallint(6) NOT NULL,  `pass` text NOT NULL,  `uid` tinytext NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=cp1251;
INSERT INTO users VALUES("1","administrator_sayta","Администратор сайта","200","0","0","admin","dima.am@mail.ru","1","21232f297a57a5a743894a0e4a801fc3","647285f5e2b2f9cc02d728241316762b");
INSERT INTO users VALUES("3","editor","editor","400","0","0","editor","dima.am@mail.ru","0","5aee9dbd2a188839105073571bee1b1f","");
